### PR TITLE
fix angled place and low angled wall selection box

### PR DESCRIPTION
**Pull request by pithydon**
You broke angled place :P
I added a comment in the code to help you understand the angled place function.

### CODE REVIEW

**Comment by TumeniNodes** [comment]
uh oh, how did I break it? I'm very sorry
I will take a look to see what I missed before I merge it

**Comment by TumeniNodes** [comment]
I think I have to go and add these lines in the bakedclay and quartz luas as well.
Now, I learned that my way of using githubs online drop n drag is incorrect use of git. Am I messing you up when I do this?
So far, I only know how to use CL for cloning a git repo. : /
I am reading up on Sofar's "how to use git" info so I can start doing this right.

**Comment by TumeniNodes** [comment]
I am merging your PR now, thank you very much.
And I am going to add the lines in the other luas as needed.
Then I will try to use the CL to push the updates
Edit\* just realized I do not need to add the lines in the other luas... (slowly getting it haha)
I'm concerned you do not show up as a contributor? Is there something I have not done correctly to show you as a contributor?
And lastly, why does low angled wall require a selection-box, when the other2 use collision-box? I'm asking as I do not understand that part and would like to know.
Thank you so much for all the help you have given

**Comment by pithydon** [comment]
The selection-box is the box used for selecting a node.
You have to point your mouse at the selection-box to select it.
Because the low angled wall is only half a block tall I made the selection-box half a block tall.
By default the selection-box is a full block or the node-box.

**Comment by TumeniNodes** [comment]
That makes sense now. Thanks

**Pull request merged**
