### PR TITLE
Make placement of nodes angled to.

### PR DESCRIPTION
**Pull request by pithydon**
I found the previous placement to be confusing.

### CODE REVIEW

**Comment by TumeniNodes** [comment]
I'll check this out today

**Comment by TumeniNodes** [comment]
Updates are committed. This caused conflicts as you suspected. Changes are ready for you to review. Thank you

**Comment by pithydon** [comment]
Looks ready to merge.

**Comment by TumeniNodes** [comment]
merged. Thank you

**Pull request merged**
