### PR TITLE
Fix angled walls

### PR DESCRIPTION
**Pull request by An0n3m0us**
Fixed glitchy faces by moving the the top face down and the bottom face up; both by a tiny value of (0.0002). Also fixed the bottom texture  looking dark.

Thirdly, I fixed the UVs to make the textures look nicer. The three front faces use the whole texture but without overlapping or using parts only. The old UV twice used the right side of the texture which made it look a bit odd.

<details><summary>Images (click to uncollapse)</summary>
<p>

OLD:
test1

NEW:
test2

</p>
</details>

### CODE REVIEW

**Comment by TumeniNodes** [comment]
Thank you so much, this was my next project.
This looks _very_ nice and I definitely appreciate the time put into it.
Let me test your branch (probably tomorrow for me) and if all works fine, I will merge.
Again, thank you _very_ much

**Comment by An0n3m0us** [comment]
You are welcome : )

**Comment by An0n3m0us** [comment]
You're welcome.

**Comment by TumeniNodes** [comment]
I was actually eager to see the results, late last night.
I have only two requests.
1. The bottom UV is too bright, they need to be toned down to match other sides. However, with the way lighting works in MT the undersides of nodes are normally a bit darker.

2. Would you mind rotating the top and bottom UVs to match (line up) with the basic node's textures?

Other than these, it looks great.

**Comment by An0n3m0us** [comment]
1. I tried that already, but I'm not sure how to fix that. Also, if you noticed before, it was like that for the top face too; my changes didn't cause that to happen. Although, I'll have another look : )
EDIT: I forgot to mention; this happens for the glass texture only.
EDIT2: I don't think it is possible to fix this. I'm not sure how, anyway.

2. For which wall type shall I do it?

**Comment by TumeniNodes** [comment]
1. Hmmm, looking at the original mod the light levels were normal for the nodes both top and bottom sides. Did you replace the .blend files with yours (I did not look to see, sorry)? If so I can have a look to see what happened.

2. rotating the top and bottom UVs were not part of your PR, I just figured Id take advantage ; ) so I added it as a request because I am lazy : D
 It would entail doing so for all 3 angled wall nodes, as I overlooked that in the original mod.
 Of course you do not have to do it, I can always do it in another push later, it is not a killer for this PR :)

**Comment by An0n3m0us** [comment]
1. No I didn't replace the Blender file. I just edited it. These are the original from your repository:
<details><summary>Images (click to uncollapse)</summary>
<p>

test
test

</p>
</details>

2. You're tryna persuade me to do it xD
I don't mind doing it in this pull request or another. Rotating it to where? It's aligned correctly as far as I can see.

**Comment by An0n3m0us** [comment]
They are shaded the same:
Both models:
Original:
test

New (edited original like before but without fixing side face textures (3rd fix that I did above) so we can see the same textures):
test2

**Comment by An0n3m0us** [comment]
New fix:
Side glitches (notice face against tree). I fixed it for all three walls where they needed it.

<details><summary>Images (click to uncollapse)</summary>
<p>

ORIGINAL:
test

NEW:
test2

</p>
</details>

**Comment by TumeniNodes** [comment]
The alignment issue was my mistake sorry. The top & bottom textures only align when placed facing North (which is normal behavior), which I am not sure even adding the 'use_global_textures' could fix as these are mesh, not nodes. So don't worry about that.

The latest fix for the z-sorting with glass was a nice catch, thank you.

The _only_ issue remaining, is the fact that the bottom textures are so much brighter now, when they should be darker.

<details><summary>Images (click to uncollapse)</summary>
<p>

screenshot_20190613_015419

<p>
</details>

You had mentioned in the original comment for this PR
" Also fixed the bottom texture looking dark."
If this can be reverted it would be perfect. Meaning the bit regarding the bottom texture.

**Comment by An0n3m0us** [comment]
My mistake; I was looking from beneath at 'bottom' faces only, not their other side.

Done!
test

**Comment by TumeniNodes** [comment]
This is great, I love this PR, thank you again for the time and effort, nice work.
Will merge today and update on CDB & the forum.

**Comment by An0n3m0us** [comment]
You're welcome.

**Pull request merged**
